library(ggplot2)
library(data.table)
library(grid)
library(gridExtra)
library(dplyr)
library(reshape2)

# Load data and models
# We need to load the models from the .RData files generated by the previous script
# We will focus on the "New Var" set for now as per the discussion context

# Define paths and variables
base_dir <- "03-model-comparison-combined-new-var"
output_dir <- "03-model-comparison-combined-new-var"
dependent_vars <- c("peak_preval", "peak_time", "gentime", "rep_num")
dependent_vars_labels <- c("Peak Prevalence", "Peak Time", "Generation Time", "Reproductive Number")

# Helper function to extract model data
extract_model_data <- function(models_list) {
  aic_values <- unlist(lapply(models_list, function(x) x$aic))
  bic_values <- unlist(lapply(models_list, function(x) x$bic))
  formulas <- as.character(unlist(lapply(models_list, function(x) x$formula)))
  
  df <- data.frame(
    id = 1:length(models_list),
    aic = aic_values,
    bic = bic_values,
    formula = formulas,
    stringsAsFactors = FALSE
  )
  
  # Calculate Z-scores
  mean_AIC <- mean(aic_values)
  mean_BIC <- mean(bic_values)
  sd_AIC <- sd(aic_values)
  sd_BIC <- sd(bic_values)
  
  df$AIC_z <- (df$aic - mean_AIC) / sd_AIC
  df$BIC_z <- (df$bic - mean_BIC) / sd_BIC
  df$Mean_z <- rowMeans(df[, c("AIC_z", "BIC_z")])
  
  # Rank models
  df <- df[order(df$Mean_z), ]
  df$rank <- 1:nrow(df)
  
  return(df)
}

# Helper function to check significance
check_significance <- function(model_obj, var_name) {
  if (!is.null(model_obj$p_vals) && var_name %in% names(model_obj$p_vals)) {
    return(model_obj$p_vals[var_name] < 0.05)
  } else if (is.null(model_obj$p_vals)) {
    # Fallback for old data without p-values
    return(var_name %in% labels(terms(as.formula(model_obj$formula))))
  }
  return(FALSE)
}

# Main plotting function
create_matrix_plot <- function(dep_var, label) {
  rdata_file <- file.path(base_dir, paste0("03-combined_models_", dep_var, ".RData"))
  
  if (!file.exists(rdata_file)) {
    message(paste("File not found:", rdata_file))
    return(NULL)
  }
  
  models_list <- readRDS(rdata_file)
  models_list <- Filter(Negate(is.null), models_list)
  
  model_stats <- extract_model_data(models_list)
  
  # Select top 50% models
  n_total <- nrow(model_stats)
  n_top50 <- floor(0.50 * n_total)
  top_models_df <- model_stats[1:n_top50, ]
  
  # Define Q groups for coloring
  n_top10 <- floor(0.10 * n_total)
  n_top25 <- floor(0.25 * n_total)
  
  top_models_df$Q_group <- "Q_50"
  top_models_df$Q_group[top_models_df$rank <= n_top25] <- "Q_25"
  top_models_df$Q_group[top_models_df$rank <= n_top10] <- "Q_10"
  
  # Identify all unique variables (terms) across these top models
  # We need to parse the formulas to get the exact terms (e.g., "I(variance^2)")
  all_terms <- unique(unlist(lapply(top_models_df$formula, function(f) {
    attr(terms(as.formula(f)), "term.labels")
  })))
  all_terms <- all_terms[all_terms != "I(factor(nettype))"] # Exclude fixed effects from rows
  
  # Build the matrix data
  matrix_data <- list()
  
  for (i in 1:nrow(top_models_df)) {
    model_idx <- top_models_df$id[i] # Original index in models_list
    model_obj <- models_list[[model_idx]]
    rank <- top_models_df$rank[i]
    q_group <- top_models_df$Q_group[i]
    
    for (term in all_terms) {
      is_sig <- check_significance(model_obj, term)
      if (is_sig) {
        matrix_data[[length(matrix_data) + 1]] <- data.frame(
          rank = rank,
          term = term,
          Q_group = q_group,
          present = TRUE
        )
      }
    }
  }
  
  matrix_df <- do.call(rbind, matrix_data)
  
  # Clean up term names for display
  clean_terms <- function(x) {
    x <- gsub("igraph_", "", x)
    x <- gsub("avg_", "Avg. ", x)
    x <- gsub("local_", "Local ", x)
    x <- gsub("degree_variance", "Variance", x)
    x <- gsub("assortativity", "Assortativity", x)
    x <- gsub("path_length", "Path Length", x)
    x <- gsub("transitivity", "Transitivity", x)
    x <- gsub("modularity", "Modularity", x)
    x <- gsub("I\\((.*)\\^2\\)", "[\\1^2]", x)
    x <- gsub("log\\((.*)\\)", "Log(\\1)", x)
    return(x)
  }
  
  matrix_df$term_label <- clean_terms(matrix_df$term)
  
  # Calculate frequencies for the left panel (Bar Chart)
  # We need to count how many times each term appears in each Q group
  # Note: Q_10 is a subset of Q_25, which is a subset of Q_50.
  # The bar chart usually stacks them: 
  # Bottom bar (Red): Count in Q_10
  # Middle bar (Green): Count in Q_25 - Count in Q_10
  # Top bar (Blue): Count in Q_50 - Count in Q_25
  
  term_counts <- matrix_df %>%
    group_by(term_label, Q_group) %>%
    summarise(count = n(), .groups = 'drop')
  
  # We need to normalize these counts by the total number of models in that Q group?
  # The original plot used "Sum of Frequencies" where frequency was count / num_models_in_Q.
  # Let's replicate the logic from the previous script exactly for the left panel.
  
  # Re-calculate frequencies exactly as in the original script logic
  # But now we have specific terms (functional forms), not just variables.
  
  # Total models in each threshold
  N_Q10 <- n_top10
  N_Q25 <- n_top25
  N_Q50 <- n_top50
  
  # Counts per term per threshold
  counts_Q10 <- matrix_df %>% filter(rank <= N_Q10) %>% group_by(term_label) %>% summarise(n = n())
  counts_Q25 <- matrix_df %>% filter(rank <= N_Q25) %>% group_by(term_label) %>% summarise(n = n())
  counts_Q50 <- matrix_df %>% filter(rank <= N_Q50) %>% group_by(term_label) %>% summarise(n = n())
  
  # Merge and fill zeros
  all_term_labels <- unique(matrix_df$term_label)
  freq_data <- data.frame(term_label = all_term_labels)
  
  freq_data <- merge(freq_data, counts_Q10, by="term_label", all.x=TRUE); colnames(freq_data)[2] <- "n_Q10"
  freq_data <- merge(freq_data, counts_Q25, by="term_label", all.x=TRUE); colnames(freq_data)[3] <- "n_Q25"
  freq_data <- merge(freq_data, counts_Q50, by="term_label", all.x=TRUE); colnames(freq_data)[4] <- "n_Q50"
  freq_data[is.na(freq_data)] <- 0
  
  # Calculate frequencies (proportions)
  freq_data$freq_Q10 <- freq_data$n_Q10 / N_Q10
  freq_data$freq_Q25 <- freq_data$n_Q25 / N_Q25
  freq_data$freq_Q50 <- freq_data$n_Q50 / N_Q50
  
  # Prepare data for stacked bar plot
  # The "stacking" in the original plot was a bit specific. 
  # It plotted Q_50 bar, then Q_25 on top (or over), then Q_10.
  # Since Q_10 is a subset, if we want to show the contribution, we usually plot the largest first, then overlay the smaller ones.
  # Let's create a long format for ggplot
  
  freq_long <- melt(freq_data[, c("term_label", "freq_Q10", "freq_Q25", "freq_Q50")], 
                    id.vars = "term_label", variable.name = "Q_group", value.name = "frequency")
  
  freq_long$Q_group <- factor(freq_long$Q_group, levels = c("freq_Q50", "freq_Q25", "freq_Q10"))
  
  # Order terms by total frequency (sum of frequencies across groups, or just Q_50 frequency?)
  # The original script ordered by sum of frequencies.
  freq_data$total_freq_sum <- freq_data$freq_Q10 + freq_data$freq_Q25 + freq_data$freq_Q50
  ordered_terms <- freq_data$term_label[order(freq_data$total_freq_sum, decreasing = FALSE)] # Ascending for coord_flip
  
  freq_long$term_label <- factor(freq_long$term_label, levels = ordered_terms)
  matrix_df$term_label <- factor(matrix_df$term_label, levels = ordered_terms)
  
  # --- Plot 1: Left Panel (Bar Chart) ---
  p_left <- ggplot(freq_long, aes(x = term_label, y = frequency, fill = Q_group)) +
    geom_bar(stat = "identity", position = "stack") + # Stack accumulates them
    scale_fill_manual(values = c("freq_Q50" = "deepskyblue3", "freq_Q25" = "chartreuse3", "freq_Q10" = "red"),
                      labels = c("50%", "25%", "10%")) +
    coord_flip() +
    scale_y_reverse() + # Reverse axis to point towards the matrix
    theme_minimal() +
    theme(
      legend.position = "none",
      axis.text.y = element_text(size = 10),
      axis.title.y = element_blank(),
      axis.title.x = element_text(size = 10),
      panel.grid.major.y = element_blank()
    ) +
    labs(y = "Sum of Frequencies")
  
  # --- Plot 2: Right Panel (The Matrix) ---
  p_right <- ggplot(matrix_df, aes(x = rank, y = term_label)) +
    geom_point(aes(color = Q_group), size = 3, shape = 15) + # Square dots
    scale_color_manual(values = c("Q_50" = "deepskyblue3", "Q_25" = "chartreuse3", "Q_10" = "red")) +
    scale_x_continuous(breaks = seq(1, n_top50, by = 5), expand = c(0.02, 0.02)) +
    theme_bw() +
    theme(
      legend.position = "right",
      axis.text.y = element_blank(), # Hide Y labels (they are on the left plot)
      axis.ticks.y = element_blank(),
      axis.title.y = element_blank(),
      panel.grid.major.y = element_line(color = "grey90"), # Horizontal lines to guide eye
      panel.grid.minor = element_blank()
    ) +
    labs(x = "Model Rank (Best to Worst)", color = "Top Q%")
  
  # Combine plots
  # We use grid.arrange to put them side by side
  # The left plot needs more width for labels
  
  pdf_file <- file.path(output_dir, paste0("Matrix_Plot_", label, ".pdf"))
  pdf(pdf_file, width = 12, height = 8)
  grid.arrange(p_left, p_right, ncol = 2, widths = c(1, 2), 
               top = textGrob(paste("Model Stability Matrix:", label), gp = gpar(fontsize = 16, fontface = "bold")))
  dev.off()
  
  message(paste("Generated matrix plot for", label))
}

# Run for all dependent variables
for (i in seq_along(dependent_vars)) {
  create_matrix_plot(dependent_vars[i], dependent_vars_labels[i])
}
