---
format: html
title: Sunbelt 2023 presentation
subtitle: "Differences in differences in network statistics"
embed-resources: true
execute: 
  warning: false
---

## Pairwise comparisons with the original network

We first reload the original data to take the raw values

```{r}
library(data.table)
simstats <- fread("data/02-dataprep-network-stats.csv.gz")
```

Preparing the data for the pairwise comparisons

```{r}
# Computing the average for all variables in simstats by network type and id
simstats_bynet <- simstats[, lapply(.SD, mean, na.rm = TRUE), by = .(nettype, netid), .SDcols = setdiff(colnames(simstats), c("nettype", "netid"))]

# Generating IDs based on the original
original_id <- simstats[, as.list(range(netid)), by = nettype]
setnames(original_id, c("V1", "V2"), c("netid_min", "netid_max"))

# Merging the IDs with the bynet dataset
simstats_bynet <- merge(simstats_bynet, original_id, by = "nettype")

# Generating new id by subtracting the minimum id from the original
# and adding 1 to avoid 0
simstats_bynet[, net := netid - netid_min + 1]

# Creating the dependent variables
igraph_vars <- grep("^igraph", names(simstats), value = TRUE)
ergm_vars <- grep("^ergm", names(simstats), value = TRUE)
depvars <- c(
  "peak_time", "peak_preval", "rt", "dispersion", "final_preval")
diffvars <- c(depvars, ergm_vars, igraph_vars)

simstats_bynet <- merge(
  simstats_bynet,
  simstats_bynet[nettype == "ergm",.SD, .SDcols = c(diffvars, "net")],
  by = "net", suffixes = c("", "_ergm")
  )

# Preserving complete cases
simstats_bynet <- simstats_bynet[complete.cases(simstats_bynet)]

```

We now create dependent variables as the difference between  \* and \*_ergm

```{r}
for (depvar in diffvars) {
  simstats_bynet[, paste0(depvar, "_diff") := get(depvar) - get(paste0(depvar, "_ergm"))]
}

# Removing the rows where nettype equals ergm
simstats_bynet <- simstats_bynet[nettype != "ergm"]

# Scaling variables starting with ergm or igraph using na.rm = TRUE
igraph_vars <- grep("^igraph", names(simstats_bynet), value = TRUE)
simstats_bynet[, (igraph_vars) := lapply(.SD, scale), .SDcols = igraph_vars]

ergm_vars <- grep("^ergm", names(simstats_bynet), value = TRUE)
simstats_bynet[, (ergm_vars) := lapply(.SD, scale), .SDcols = ergm_vars]


# Generating a list of models
models <- list()
depvars2 <- paste0(depvars, "_diff")
modelvalrs <- paste0(c(ergm_vars, igraph_vars), "_diff")
baseline <- paste("~ I(factor(nettype)) + ", paste(modelvalrs, collapse = " + ")) |>
  as.formula()
for (depvar in depvars2) {
  models[[depvar]] <- update(baseline, paste(depvar, "~."))
}

# Running the models
models <- lapply(models, glm, data = simstats_bynet)
```

```{r}
#| echo: false
#| output: asis
texreg::knitreg(models, single.row = TRUE)
```